### ISSUE TITLE
Faire archi metier

### ISSUE THREAD

**Issue by oRiamn** [oRiamn/epsi-expert-system#11]

**Comment by sylvainmetayer** [comment]
@oRiamn Regarde l'état de la branche poc_express et dis moi ce que tu en penses.

**Comment by sylvainmetayer** [comment]
@oRiamn on peut considérer que c'est bon avec ce qui a été fait dans  #15 ?

**Comment by sylvainmetayer** [comment]
Archi validée !! @oRiamn
